CREATE DATABASE RAILWAYRESERVATION;
USE  RAILWAYRESERVATION;
CREATE TABLE Users (
        UserID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        UserName VARCHAR(15) UNIQUE NOT NULL,
        Password VARCHAR(15) NOT NULL,
        Email VARCHAR(50) UNIQUE NOT NULL,
        FirstName VARCHAR(15),
        LastName VARCHAR(15),
        DateOfBirth VARCHAR(10),
        Age INT,
        MobileNo VARCHAR(10),
       DateTimeOfBooking VARCHAR(30) NOT NULL
 );
CREATE TABLE Trains_info (
       TrainID INT PRIMARY KEY,
       TrainNumber VARCHAR(15) UNIQUE NOT NULL,
       TrainName VARCHAR(50) NOT NULL,
       DepartureTime VARCHAR(10),
       Distance DECIMAL(10, 2),
       ArrivalTime VARCHAR(10),
      Source VARCHAR(50),
      Destination VARCHAR(50),
      SeatAvailability INT,
      DateTimeOfBooking VARCHAR(30) NOT NULL
  );
 CREATE TABLE TrainRoutes (
        RouteID INT PRIMARY KEY,
        TrainID INT,
        StopNo INT,
        StopName VARCHAR(50),
        FOREIGN KEY (TrainID) REFERENCES Trains_info(TrainID),
        DateTimeOfBooking VARCHAR(30) NOT NULL
    );
 CREATE TABLE TrainClasses (
        ClassID INT PRIMARY KEY,
        TrainID INT,
        Fare DECIMAL(10, 2) NOT NULL,
        ClassType VARCHAR(10) CHECK (ClassType IN ('General', 'Sleeper', '1AC', '2AC', '3AC')) NOT NULL,
        TrainNumber VARCHAR(15) NOT NULL,
        FOREIGN KEY (TrainID) REFERENCES Trains_info(TrainID),
        DateTimeOfBooking VARCHAR(30) NOT NULL
    );
 CREATE TABLE Tickets (
       TicketID INT PRIMARY KEY,
       UserID INT,
       PNRNo VARCHAR(10) UNIQUE NOT NULL,
       SeatNo VARCHAR(10) NOT NULL,
      Destination VARCHAR(50) NOT NULL,
      Source VARCHAR(50) NOT NULL,
      Class VARCHAR(10) CHECK (Class IN ('General', 'Sleeper', '1AC', '2AC', '3AC')) NOT NULL,
      PassengerName VARCHAR(50) NOT NULL,
      DateTimeOfBooking VARCHAR(30) NOT NULL,
      TrainNumber VARCHAR(15) NOT NULL,
      Status VARCHAR(10) DEFAULT 'Booked' CHECK (Status IN ('Booked','Cancelled')),
      FOREIGN KEY (UserID) REFERENCES Users(UserID)
  );
 CREATE TABLE Payment (
        PaymentID INT PRIMARY KEY,
        TicketID INT UNIQUE,
        Bank VARCHAR(50),
        CardNo VARCHAR(16),
        TransactionID VARCHAR(50),
        Amount DECIMAL(10, 2),
        FOREIGN KEY (TicketID) REFERENCES Tickets(TicketID),
        DateTimeOfBooking VARCHAR(30) NOT NULL
   );
CREATE TABLE Trains_info (
    TrainID INT PRIMARY KEY,
    TrainNumber VARCHAR(15) UNIQUE NOT NULL,
    TrainName VARCHAR(50) NOT NULL,
    DepartureTime VARCHAR(10), 
    Distance DECIMAL(10, 2),
    ArrivalTime VARCHAR(10); 
    Source VARCHAR(15),
    Destination VARCHAR(15),
    SeatAvailability INT
);
CREATE TABLE TrainRoutes (
    RouteID INT PRIMARY KEY,
    TrainID INT,
    StopNo INT,
    StopName VARCHAR(15),
    FOREIGN KEY (TrainID) REFERENCES Trains_info(TrainID)
);
CREATE TABLE TrainClasses (
    ClassID INT PRIMARY KEY,
    TrainID INT,
    Fare DECIMAL(10, 2) NOT NULL,
    ClassType VARCHAR(10) CHECK (ClassType IN ('General', 'Sleeper', '1AC', '2AC', '3AC')) NOT NULL,
    TrainNumber VARCHAR(15) NOT NULL,
    FOREIGN KEY (TrainID) REFERENCES Trains_info(TrainID)
);
CREATE TABLE Tickets (
    TicketID INT PRIMARY KEY,
    UserID INT,
    PNRNo VARCHAR(10) UNIQUE NOT NULL,
    SeatNo VARCHAR(10) NOT NULL,
    Destination VARCHAR(15) NOT NULL,
    Source VARCHAR(15) NOT NULL,
    Class VARCHAR(10) CHECK (Class IN ('General', 'Sleeper', '1AC', '2AC', '3AC')) NOT NULL,
    PassengerName VARCHAR(15) NOT NULL,
    DateTimeVARCHAR(10) NOT NULL,
    TrainNumber VARCHAR(15) NOT NULL,
    Status VARCHAR(10) DEFAULT 'Booked' CHECK (Status IN ('Booked', 'Cancelled')),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
CREATE TABLE Payment (
    PaymentID INT PRIMARY KEY,
    TicketID INT UNIQUE,
    Bank VARCHAR(15),
    CardNo VARCHAR(16),
    TransactionID VARCHAR(15),
    Amount DECIMAL(10, 2),
    FOREIGN KEY (TicketID) REFERENCES Tickets(TicketID)
);
-- Join Users table with Tickets table
SELECT * 
FROM Users u
JOIN Tickets t ON u.UserID = t.UserID;
-- Join Users table with Payment table
SELECT * 
FROM Users u
JOIN Payment p ON u.UserID = p.UserID_Payment;
-- Join Trains table with Tickets table
SELECT * 
FROM Trains tr
JOIN Tickets t ON tr.TrainNumber = t.TrainNumber;
-- Join Trains table with TrainRoutes table
SELECT * 
FROM Trains tr
JOIN TrainRoutes trr ON tr.TrainID = trr.TrainID;
-- Join Trains table with TrainClasses table
SELECT * 
FROM Trains tr
JOIN TrainClasses tc ON tr.TrainID = tc.TrainID;
-- Join TrainRoutes table with Trains table
SELECT * 
FROM TrainRoutes trr
JOIN Trains tr ON trr.TrainID = tr.TrainID;
-- Join TrainClasses table with Trains table
SELECT * 
FROM TrainClasses tc
JOIN Trains tr ON tc.TrainID = tr.TrainID;
-- Join Tickets table with Users table
SELECT * 
FROM Tickets t
JOIN Users u ON t.UserID = u.UserID;
-- Join Tickets table with Trains table
SELECT * 
FROM Tickets t
JOIN Trains tr ON t.TrainNumber = tr.TrainNumber;
-- Join Tickets table with Payment table
SELECT * 
FROM Tickets t
JOIN Payment p ON t.TicketID = p.TicketID;
-- Join Payment table with Users table & Payment table with Tickets table
SELECT u.*, p.Bank, p.CardNo, p.TransactionID, p.Amount
FROM Users u
JOIN Tickets t ON u.UserID = t.UserID
JOIN Payment p ON t.TicketID = p.TicketID;

